### ISSUE TITLE
One thousand issues and PRs later...

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#1000]
can devs do something?

**Comment by brunovjk** [comment]
Can I help?

**Comment by jaybuidl** [comment]
Feel free to pick up on of these "good first issues" @brunovjk
https://github.com/kleros/kleros-v2/labels/Good%20First%20Issue%20%F0%9F%8E%AC

**Comment by brunovjk** [comment]
Thank you. I will!
