### ISSUE TITLE
UX: Add the ArbitrumGoerli/Arbitrum network to the user's wallet if needed

### ISSUE THREAD

**Issue by AtharvaMaskar26** [kleros/kleros-v2#1038]
Not able to connect to Arbitrum Goerli if it is not added manually to metamask. 

https://github.com/kleros/kleros-v2/assets/107984209/9ce4b85d-a5c2-4268-b9fc-bf7abe669854

Perfectly working after manually entering network details into metamask

**Comment by AtharvaMaskar26** [comment]
Can I take on this issue?

**Comment by jaybuidl** [comment]
Okay we could use `wallet_addEthereumChain` if needed. 

cc: @alcercu @kemuru @nhestrompia

**Comment by jaybuidl** [comment]
Just tested this and confirmed it works
