### ISSUE TITLE
Gamification: buttons to let the user share their score on social media

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#1061]
On the Dashboard page, add social buttons to share a screenshot of your score on Twitter/X, Lens, Farcaster...
![image](https://github.com/kleros/kleros-v2/assets/22213980/cd892639-c41c-45d1-a3f6-dc9c8b96ed3f)

## Twitter
[Button generator](https://publish.twitter.com/?buttonRecommendation=kleros_io&buttonText=Hey%20I%27ve%20been%20busy%20as%20a%20Juror%20on%20the%20Kleros%20court%2C%20check%20out%20my%20score%21&buttonType=TweetButton&widget=Button)
https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview
https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/web-intent
![image](https://github.com/kleros/kleros-v2/assets/22213980/dbe3499a-5a01-43f4-83c5-ada3f02f5728)

## Lens
https://docs.lens.xyz/docs/integrating-lens
https://docs.lens.xyz/docs/lens-widgets#share-to-lens
![image](https://github.com/kleros/kleros-v2/assets/22213980/40300d4a-5e6a-4662-a398-d2bdd7c2369c)

## Farcaster
https://github.com/standard-crypto/farcaster-js#publish-a-cast

**Comment by Arun9650** [comment]
hello, i like to take this task

**Comment by Arun9650** [comment]
hello, I have a question. my local dashboard is different from your, why is that .
![image](https://github.com/kleros/kleros-v2/assets/76466509/c7c02984-6703-4e34-8528-f7b21c5f3a66)

**Comment by ptdatta** [comment]
@jaybuidl , pls check this [PR](https://github.com/kleros/kleros-v2/pull/1114)
