### ISSUE TITLE
Update the start-local script (kleros-v2/web)

### ISSUE THREAD

**Issue by Zishan-7** [kleros/kleros-v2#1065]
### Issues : 
- The current start-local script just spins up the server on localhost with this command 
`REACT_APP_SUBGRAPH_ENDPOINT=http://localhost:8000/subgraphs/name/kleros/kleros-v2-core-local parcel`
But this command alone does not compile the `wagami.config.ts` file. That results in compile-time errors like this :

<img width="987" alt="Screenshot 2023-07-28 at 12 24 51 PM" src="https://github.com/kleros/kleros-v2/assets/72738005/87eab551-e53f-4c4d-a138-b4361be0af44">

### Solution : 
To fix this issue need to run the `generate-hooks` command before starting the server  : 

```diff

- "start-local": "REACT_APP_SUBGRAPH_ENDPOINT=http://localhost:8000/subgraphs/name/kleros/kleros-v2-core-local parcel"
+ "start-local": "yarn generate-hooks && REACT_APP_SUBGRAPH_ENDPOINT=http://localhost:8000/subgraphs/name/kleros/kleros-v2-core-local parcel" 

```

**Comment by jaybuidl** [comment]
It should work now, I've updated the docs and tmux script. I don't want to change the `start-local` and `start` behaviour because it would slow down the devs workflow whenever they make changes which don't require to generate.

```bash
yarn workspace @kleros/kleros-v2-web generate
...

yarn workspace @kleros/kleros-v2-web start-local
...
```
