### ISSUE TITLE
Missing script for Subgraph deployment in local environment (kleros-v2/subgraph)

### ISSUE THREAD

**Issue by Zishan-7** [kleros/kleros-v2#1066]
### Issue

While deploying the subgraph to the local environment I followed the steps mentioned in the readme file : 

**Step 1:**  `yarn workspace @kleros/kleros-v2-contracts start-local`
**Step 2:**  `yarn workspace @kleros/kleros-v2-subgraph start-local-indexer`

But while running this command: `yarn workspace @kleros/kleros-v2-subgraph rebuild-deploy-local`
I am facing this issue

<img width="699" alt="Screenshot 2023-07-28 at 12 18 40 PM" src="https://github.com/kleros/kleros-v2/assets/72738005/52c496a9-72c5-49c3-aef1-7b9a1647cf1b">

### Reason

`rebuild-deploy-local` script runs `yarn update` but there is no `update` script present in `subgraph/package.json` file

**Comment by jaybuidl** [comment]
It should work now @Zishan-7
