### ISSUE TITLE
Reflow the stats icons to lines of 4 items (desktop only)

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#1075]
This is the main UX issue when using the frontend on desktop and the best place to start improve desktop friendliness.

The list of statistics is currently a long vertical list of 4 or 8 icons and metrics, which requires too much scrolling on desktop.

| | Home screen | Court |
| --- | --- | --- |
| **Current** | ![image](https://github.com/kleros/kleros-v2/assets/22213980/18befb0e-96ce-4a2c-bd32-126be8642b13) | ![image](https://github.com/kleros/kleros-v2/assets/22213980/14650692-c939-453c-91f6-3f85d91de137) |
| **Expected** | ![image](https://github.com/kleros/kleros-v2/assets/22213980/5dd51774-7fb6-4173-a1ef-7c428c9fdae7) | ![image](https://github.com/kleros/kleros-v2/assets/22213980/74df0d9f-349c-470c-bfac-89ab885da220) |

**Comment by Zishan-7** [comment]
Hey @jaybuidl 
I would like to work on this issue, can you assign it to me?

**Comment by jaybuidl** [comment]
Done!

**Comment by ptdatta** [comment]
Hey @jaybuidl, Is this still open??
