### ISSUE TITLE
Voting tab: number of jurors who votes is incorrect when a juror is drawn several times

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#1095]
I have been drawn 2 times out 3 on this case but the frontend says that only 1 juror has voted.

The `castVote()` [transaction](https://goerli.arbiscan.io/tx/0x875c4c759683e3706ac0b885fc76ef36e92d0361a129c6ce2e3ad527abbbc49c) shows that 2 votes have indeed been cast.

https://deploy-preview-1057--kleros-v2.netlify.app/#/cases/86/voting

<img width="1118" alt="image" src="https://github.com/kleros/kleros-v2/assets/22213980/8b5e48c9-7cf5-46a1-8ae5-d8d89321fad1">

---

It looks like this is returning the wrong value

https://github.com/kleros/kleros-v2/blob/a7ee03ea01acd4acb699f2143c68c6f5a856e8e0/web/src/pages/Cases/CaseDetails/Voting/VotingHistory.tsx#L115

Seems the subgraph is returning the wrong result
![image](https://github.com/kleros/kleros-v2/assets/22213980/e6d43cfa-7c74-44ce-8f11-623181faf2a8)

**Comment by alcercu** [comment]
temporarily solved by #1099
