### ISSUE TITLE
Incorrect Locked PNK amount

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#1149]
Juror [0x36b6c8fe413ba60c0db27b2a67a3a0e4cd97b651](https://goerli.arbiscan.io/address/0x36b6c8fe413ba60c0db27b2a67a3a0e4cd97b651) is missing 9850 PNK. 

There should be 300 PNK locked across 2 disputes but the contract says only 150 locked.

[Context](https://t.me/c/1654173792/7463)

**Comment by shotaronowhere** [comment]
The same bug as addressed in this #1148 , affects lockedPNK, the lockedPNK is set for the court in which the dispute originates, even if the juror is staked in a lower court. . . this may require kleros core to be redeployed. . .

**Comment by kemuru** [comment]
was this fixed with the latest redeployments?
