### ISSUE TITLE
Web: let the user know the dispute is on last round...

### ISSUE THREAD

**Issue by kemuru** [kleros/kleros-v2#1183]
...and appeal is not possible anymore. Instead of showing these large numbers on the Appeal tab, we should think of something else

![IMG_1910](https://github.com/kleros/kleros-v2/assets/102478601/e7cfe79c-112f-444f-a4e6-baefe760ec12)

**Comment by jaybuidl** [comment]
### Solution

This is a temporary solution until the forking court is implemented. It is unlikely to happen in mainnet conditions (arbitrum one), but quite likely on a testnet.

If the appealCost() returns anything >= (2 ** 154)/2, then disable the appeal tab with a message: "This dispute cannot be appealed any further."

**Comment by kemuru** [comment]
fixed on PR #1184
