### ISSUE TITLE
Court stats: incorrect number of cases in progress

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#1193]
Expected: 0
Actual: 12

https://v2.kleros.builders/#/courts/1/purpose

![image](https://github.com/kleros/kleros-v2/assets/22213980/78a76b73-d79f-4e18-8439-7957a9207dae)

**Comment by kemuru** [comment]
currently we don't have this value on the subgraph for a specific court. only for all cases across all courts (thats why in the "Cases" section is shows In Progress Cases correctly, but only for all cases across all courts)
