### ISSUE TITLE
Court stats: same data for Min Stake and Vote Stake seems incorrect

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#1196]
![image](https://github.com/kleros/kleros-v2/assets/22213980/49dd91f6-03d4-494e-8eef-9eab494af00c)

<img width="773" alt="image" src="https://github.com/kleros/kleros-v2/assets/22213980/891e706e-1c2c-4426-a575-971e1d295fd5">

**Comment by kemuru** [comment]
fixed on PR #1200
