### ISSUE TITLE
No ability to disconnect the wallet

### ISSUE THREAD

**Issue by marsrobertson** [kleros/kleros-v2#1203]
<img width="1067" alt="image" src="https://github.com/kleros/kleros-v2/assets/44369284/913c1d26-3e3a-4850-8103-4514ad0c4d65">

**Comment by kemuru** [comment]
currently you can disconnect if you go to Settings

**Comment by marsrobertson** [comment]
I see... It is my opinion that more intuitively - make the "disconnect" button next to the address.

**Comment by kemuru** [comment]
yes in fact it was like that previously, i remember it cause i did it, i dont know why it was moved exactly

will comment it with the devs thanks
