### ISSUE TITLE
Web: possible bug? Voting limited to 100 votes?

### ISSUE THREAD

**Issue by kemuru** [kleros/kleros-v2#1208]
This user (me) was drawn for almost all the votes, ~500 votes
However after voting, it only shows 100 votes out of 512 voted.
2 possible things happening: 

1) we are voting correctly for all the drawn votes, but frontend is displaying a wrong value
2) we are voting incorrectly with a maximum of 100 votes?

![image](https://github.com/kleros/kleros-v2/assets/102478601/de6c73ab-2a72-4b8e-b789-a053edf5f12b)

**Comment by greenlucid** [comment]
This is most likely a subgraph bug, check out the subgraph query you're using to fetch the votes. The Graph will by default only return 100 entities unless you pass the maximum `first: 1000`
