### ISSUE TITLE
UX: Show the current round number on the Dispute Card

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#1218]
<img width="378" alt="image" src="https://github.com/kleros/kleros-v2/assets/22213980/988227c2-0ac9-40b8-aa6e-69612cf981cb">

**Comment by uxplin** [comment]
Updated the design on Figma including the Round on the cards. A related suggestion is changing the order the info is displayed to: Court > Category > Round > Juror Rewards > Voting Deadline; so Court is displayed first.

![Screen Shot 2023-09-04 at 15 17 25](https://github.com/kleros/kleros-v2/assets/15757255/ad69387b-64e1-473f-89c8-f7c9c3677739)
