### ISSUE TITLE
Dashboard, My Cases: pagination overflows

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#1285]
Clicking on the last page number causes the My Cases component to crash. 

Bare in mind that the total number of pages must take into account the filters applied.

https://github.com/kleros/kleros-v2/assets/22213980/5518094f-d63b-458f-9ede-a3b2b8af04c6

**Comment by Zishan-7** [comment]
Hey @jaybuidl 👋🏻 I would like to work on this issue. Can you assign it to me?
