### ISSUE TITLE
Juror Scoring: shift the levels by 1

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#1302]
We want the jurors **to start at level 1** instead of starting at level 0. 
If they perform badly, we want them to drop progressively to level 0. 

We need to tweak the score formula and check that
- The range boundaries are correct according #888 
- The score should remain fairly distributed among the jurors

Score levels:
```
[
  { scoreRange: [0, 20], level: 0, title: "Diogenes" },
  { scoreRange: [20, 40], level: 1, title: "Pythagoras" },
  { scoreRange: [40, 60], level: 2, title: "Socrates" },
  { scoreRange: [60, 80], level: 3, title: "Plato" },
  { scoreRange: [80, 100], level: 4, title: "Aristotle" },
];
```

**Comment by kemuru** [comment]
fixed on #1702
