### ISSUE TITLE
Bug: Withdrawing PNK seems to stake PNK?

### ISSUE THREAD

**Issue by kemuru** [kleros/kleros-v2#1319]
Shown in the video. Another thing to note is that balances are not the same in `Courts` than in `Dashboard/MyCourts`. Probably because of different hooks giving different balances. Maybe thats the cause of this issue? in my experience the one I used at `Dashboard/MyCourts` seems to give accurate user balance results (One thing to note is that the query from `Courts` is a `contract call`, while the one on `Dashboard/MyCourts` is a `subgraph query`)

https://github.com/kleros/kleros-v2/assets/102478601/9965af3e-2ede-4716-9c89-21c7c591d016

Update: I unstaked everything from all courts via frontend, balance is 0 on `Courts`, but balance is still existing on `Dashboard/MyCourts `

https://github.com/kleros/kleros-v2/assets/102478601/be5d4184-0723-485d-b350-3a08e49e6ec1

In the subgraph, this is the only handler modifying the `court.stake` field:

```typescript
export function updateJurorStake(jurorAddress: string, courtID: string, contract: KlerosCore, timestamp: BigInt): void {
  const juror = ensureUser(jurorAddress);
  const court = Court.load(courtID);
  if (!court) return;
  const jurorTokens = ensureJurorTokensPerCourt(jurorAddress, courtID);
  const jurorBalance = contract.getJurorBalance(Address.fromString(jurorAddress), BigInt.fromString(courtID));
  const previousStake = jurorTokens.staked;
  const previousTotalStake = juror.totalStake;
  jurorTokens.staked = jurorBalance.value0;
  jurorTokens.locked = jurorBalance.value1;
  jurorTokens.save();
  const stakeDelta = getDelta(previousStake, jurorTokens.staked);
  const newTotalStake = juror.totalStake.plus(stakeDelta);
  juror.totalStake = newTotalStake;
  court.stake = court.stake.plus(stakeDelta);
  updateStakedPNK(stakeDelta, timestamp);
  const activeJurorsDelta = getActivityDelta(previousTotalStake, newTotalStake);
  const stakedJurorsDelta = getActivityDelta(previousStake, jurorBalance.value0);
  court.numberStakedJurors = court.numberStakedJurors.plus(stakedJurorsDelta);
  updateActiveJurors(activeJurorsDelta, timestamp);
  juror.save();
  court.save();
}
```

**Comment by jaybuidl** [comment]
It was caused by #1162
https://github.com/kleros/kleros-v2/commit/73782d997022e422ec989f61aeb71bb9e79e278f#diff-473f39afc0e476a5691182ed8dfc5dfa27881820e4e6b6452d06610cd4b8cfe2L1017-L1021 
![image](https://github.com/kleros/kleros-v2/assets/22213980/7729c2df-d996-4e94-acd2-a66bcf82f493)
