### ISSUE TITLE
Escrow contract: tweak the event TransactionCreated

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#1389]
Escrow.TransactionCreated event: add the parameters `asset`, `_deadline` and `_transactionUri`.

For example
```solidity
event TransactionCreated(uint256 indexed _transactionID, 
  string _transactionUri, 
  address indexed _buyer, 
  address indexed _seller, 
  uint256 _amount, 
  string _asset, 
  uint256 _deadline
);
```

https://github.com/kleros/kleros-v2/blob/dev/contracts/src/arbitration/arbitrables/Escrow.sol#L90-L95

**Comment by kemuru** [comment]
@jaybuidl with _asset you mean the token? but since this is the general escrow, it will always be main currency of the chain you're in right, so not necessary?

**Comment by jaybuidl** [comment]
> @jaybuidl with _asset you mean the token? but since this is the general escrow, it will always be main currency of the chain you're in right, so not necessary?

For the native currency, let have `_asset = "native"`.

I want to avoid having a variable which looks the same as if it was  uninitialized, such as address(0) or string(""), to make the value more explicit and intentional. Ofc in the case of a token, _asset is the token address.

**Comment by kemuru** [comment]
> > @jaybuidl with _asset you mean the token? but since this is the general escrow, it will always be main currency of the chain you're in right, so not necessary?
> 
> For the native currency, let have `_asset = "native"`.
> 
> I want to avoid having a variable which looks the same as if it was uninitialized, such as address(0) or string(""), to make the value more explicit and intentional. Ofc in the case of a token, _asset is the token address.

yeah makes sense but, wasn't the crypto swap going to be a different smart contract than this one?

**Comment by jaybuidl** [comment]
> yeah makes sense but, wasn't the crypto swap going to be a different smart contract than this one? In my mind there was going to be 1 smart contract for General Escrow (with the only possibility of using native token) and a different smart contract for Crypto Swaps

Yeah different contracts but same interface if possible
