### ISSUE TITLE
Web: Timeline Mobile Styling

### ISSUE THREAD

**Issue by kemuru** [kleros/kleros-v2#1520]
the timeline inside a case is only optimized for desktop at the moment, looks really bad in mobile
<img width="311" alt="image" src="https://github.com/kleros/kleros-v2/assets/102478601/5d6ee076-6a86-40ee-9855-97ce278ffe62">

is the same for Escrow V2 timeline:
<img width="313" alt="Screenshot 2024-02-22 at 01 37 28" src="https://github.com/kleros/kleros-v2/assets/102478601/6b6e3501-bf46-4195-9cc1-645a86dac12d">

this should be fixed inside the [ui-components-library](https://github.com/kleros/ui-components-library) repository, then bump the npm version of the library and update the library version in kleros-v2, escrow-v2, and curate-v2 repos.

**Comment by ChinmayMhatre** [comment]
I'd like to help out. 
We  could put the texts on the right such as Case #110, arbitration fees deposited below the title in the mobile screen.
<img width="312" alt="image" src="https://github.com/kleros/kleros-v2/assets/51131670/f3f26d83-af23-4699-8f04-f492073eb3c6">

If we want to avoid single line titles in desktop as such 
<img width="1168" alt="image" src="https://github.com/kleros/kleros-v2/assets/51131670/5026bd4d-70bd-441e-a66d-114c7184df39">
We can add a character max-width of 40ch or something like so. 
<img width="1013" alt="image" src="https://github.com/kleros/kleros-v2/assets/51131670/b033564f-451d-4d7c-b14c-dd91bb4e1e71">

**Comment by jaybuidl** [comment]
Before/After
![image](https://github.com/kleros/kleros-v2/assets/22213980/d4058e41-6787-4a26-ac68-831fca79f92f)
