### ISSUE TITLE
Web: css improvement in List View

### ISSUE THREAD

**Issue by kemuru** [kleros/kleros-v2#1551]
so in Figma we have this:

<img width="453" alt="Screenshot 2024-03-27 at 12 45 15" src="https://github.com/kleros/kleros-v2/assets/102478601/2d4dc8f2-3d62-4d1d-aee5-47e9c6dbe468">

but on the App looks like this (wallet not connected):

<img width="292" alt="Screenshot 2024-03-27 at 12 45 35" src="https://github.com/kleros/kleros-v2/assets/102478601/e26ace85-2338-4615-b5f4-de367fd09b9b">

and like this (wallet connected):

<img width="495" alt="Screenshot 2024-03-27 at 12 45 43" src="https://github.com/kleros/kleros-v2/assets/102478601/e81c8d40-16e8-429c-9a83-dc941a460d1e">

Add some more padding/margin to the right, and a bit more gap between the case elements (example: between court and round, between amount and date..)
edit: Also make the font-color primaryText for the court name, which currently is blue

and I would also remove this line, feel like it looks better without it, wdyt? I did that for escrow-v2 and curate-v2
<img width="1218" alt="image" src="https://github.com/kleros/kleros-v2/assets/102478601/27091df3-3d49-442e-b43e-a4677e2b538c">

**Comment by jaybuidl** [comment]
Before / After
![image](https://github.com/kleros/kleros-v2/assets/22213980/d40696b2-44a3-4649-902c-c6f7b24a8531)
