### ISSUE TITLE
Allow jurors to override a vote commitment

### ISSUE THREAD

**Issue by donosonaumczuk** [kleros/kleros-v2#182]
Basically allow DisputeKit's `castCommit` function to be called multiple times during the commit period, each call overrides the commits of the previous one. This allows a juror to change its mind during the commit phase.

**Comment by shotaronowhere** [comment]
This sounds like a good idea to me.

**Comment by 0xferit** [comment]
This feature was forgotten it seems. I recall we wanted to implement it for v2, 2-3 years ago. It has some advantages like making implementing on-chain bribing contracts harder.

**Comment by donosonaumczuk** [comment]
Glad to see you agree with this change. I just opened a PR #190 for it!
