### ISSUE TITLE
Move more code to a Base DisputeKit

### ISSUE THREAD

**Issue by donosonaumczuk** [kleros/kleros-v2#183]
There is a good amount of functions shared by `DisputeKitClassic` and `DisputeKitSybilResistant`, that might be also shared by future dispute kits. Would be nice to move them to a base contract. I saw there is already a `BaseDisputeKit`, maybe should be one that inherit from that.

**Comment by shotaronowhere** [comment]
We have a general smart contract development guidelines to avoid inheritance patterns to improve the readability of contracts for reviews and decrease the likelihood of security bugs due to code scattered in different locations.

**Comment by jaybuidl** [comment]
As Shotaro said it goes against the organization development guidelines, although personally I would be in favor of more code reuse in some cases. 

The rationale is the same as Vyper which doesn't allow inheritance at all: "Vyper has dropped some Object-Oriented concepts such as Inheritance. The main motive was **to make contracts auditable and more secure, making less error-prone contracts**."

For the same reason we ended up inlining an abstract contract into each concrete classes in the bridge (https://github.com/kleros/kleros-v2/pull/81/commits/e23c66dad2d183454aba718ae775727c3396e22d), this change left the code looking somewhat confusing, we might have gotten the worst of both options here.

**Comment by donosonaumczuk** [comment]
I see your point. I would personally probably still opting for inheritance but I'm here to bring ideas to improve Kleros V2 not for changing your coding standards, so closing the issue makes sense for me. Thanks for taking the time answering!
