### ISSUE TITLE
Avoid justification being part of the commit

### ISSUE THREAD

**Issue by donosonaumczuk** [kleros/kleros-v2#185]
Remove the justification from the commit, as the valuable thing for the stake slash/reward is the choice.

This will make the UX better, as after avoiding the salt (see #184), the only requirement is to remember the choice. Justification can be just emitted in the reveal phase without being part of the commit.

**Comment by shotaronowhere** [comment]
See my comment about the UX #184 , we essentially already implement a similar scheme but the signature is used only to derive a salt off-chain, so there are no ecrecover calls.

**Comment by jaybuidl** [comment]
The justification did not receive enough attention in the design of v1, but it plays an important role in the arbitration process, especially when comparing Kleros to traditional justice. It was added in v2 here: https://github.com/kleros/kleros-v2/commit/2947180052bf744bd084f786d311c6dbc0c9e106

When commit/reveal is enabled, we don't want to a juror to be able to come up with a justification after seeing what other jurors has said. 

Given #184 I am not entirely sure how UX is affected on the frontend.

**Comment by jaybuidl** [comment]
Depends on #184 so closing for now.

We will revisit this if we encounter UX issues. Thanks again @donosonaumczuk !
