### ISSUE TITLE
Web3 Provider for WalletConnect

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#320]
Integrate [WalletConnect's Web3 Modal](https://web3modal.com/)

**Comment by abhiram11** [comment]
Hi!

To my understanding, the proposal is for `<ConnectButton />` to use `wagmi` instead of `@web3-react/core` or `Web3Provider from @ethersproject/providers`, right? I would like to know more about the possible changes to be made so I can make the required contributions.

Thanks : )

**Comment by Arun9650** [comment]
hello, I have integrated the Wagmi.sh to connect to the wallet.

**Comment by jaybuidl** [comment]
Thanks for your interest abhiram11 and arun9650, there was a bit more going into this, it will be covered by the migration to wagmi in PR #670.
