### ISSUE TITLE
Display the user's ENS name and avatar

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#322]
### [With Viem](https://viem.sh/docs/ens/actions/getEnsName.html)
```typescript
import { publicClient } from './client'
 
const ensName = await publicClient.getEnsName({
  address: '0xd2135CfB216b74109775236E36d4b433F1DF507B',
})
// 'wagmi-dev.eth
```

### [With Ethers](https://docs.ens.domains/dapp-developer-guide/resolving-names#reverse-resolution)
```typescript
var address = '0x1234...';
var name = await provider.lookupAddress(address);
// ethers.js automatically checks that the forward resolution matches.
```

### [With Viem](https://viem.sh/docs/ens/actions/getEnsAvatar.html)
```typescript
import { normalize } from 'viem/ens'
import { publicClient } from './client'
 
const ensText = await publicClient.getEnsAvatar({
  name: normalize('wagmi-dev.eth'),
})
// 'https://ipfs.io/ipfs/Qma8mnp6xV3J2cRNf3mTth5C8nV11CAnceVinc3y8jSbio'
```

### With Stamp.fyi
Use Snapshot's Stamp.fyi CDN to resolve avatars for ENS/Lens
https://cdn.stamp.fyi/avatar/jaybuidl.eth
https://cdn.stamp.fyi/avatar/jaybuidl.lens

### On the Settings modal
<img width="444" alt="image" src="https://user-images.githubusercontent.com/22213980/221031393-d43606e7-34dc-4247-bd78-ef7f802eebc9.png">

### On the Juror's dashboard
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/22213980/221031743-31b9f909-d216-430d-8167-7aa7a0c2c248.png">

**Comment by ptdatta** [comment]
Hey @jaybuidl , On the settings page, it's already showing the avatar does I only need to add it to the dashboard?
