### ISSUE TITLE
Remove changelog file pre-commit hook

### ISSUE THREAD

**Issue by shalzz** [kleros/kleros-v2#4]
It creates a lot of unnecessary merge/rebase conflicts and I don't really see any benefit of it when its just a `git log`

**Comment by shalzz** [comment]
@jaybuidl Wdyt?

**Comment by jaybuidl** [comment]
[KeepaChangelog.com](https://keepachangelog.com/) :)

The audience of a changelog is different than the audience of the commit messages but tbh I am also getting annoyed with the constant conflicts in the generated changelog and we are not the only ones, these guys ended up building a better tool but I haven't got time to dig into it, check it out: https://upte.ch/blog/keep-a-changelog-without-conflicts/

So the current solution is annoying but having a changelog is valuable especially as release notes for the artifacts published externally down the road such as the SDK. In principle it should be useful even [within the team](https://www.conventionalcommits.org/en/v1.0.0/#how-should-i-deal-with-commit-messages-in-the-initial-development-phase) when the number of concurrent changes increases.

So far I just keep the local version of the changelog when there is a conflict.

Ok to remove the precommit hook for now. Afaik the changelog can always be generated at release time.

**Comment by shalzz** [comment]
Sure, having a changelog is valuable but not when all it's doing is `git log --pretty=oneline > CHANGELOG.md` via complicated tooling.

In any case, yes generating the changelog should only be done at release so as to not impede the dev flow in any way. (True for any git precommit hook as it adds latency to commits in turn encourages one to batch changes into a single commit instead of maintaining individual commits as single logical changes)

**Comment by shalzz** [comment]
Was this resolved by a commit?

**Comment by jaybuidl** [comment]
It was in a branch, it's not yet merged to master. 
https://github.com/kleros/kleros-v2/commit/ba60d8fe8809a93a153cbc21dd29036060f30f26#diff-d2bc4bbf14eadc292d84e0ef5f7a93115c23557f533809fc80b896934291529d

**Comment by jaybuidl** [comment]
Cherry-picked and merged to master.
