### ISSUE TITLE
Hardcoded values: 2nd chiado in hooks/queries/useEvidenceGroup.ts

### ISSUE THREAD

**Issue by kemuru** [kleros/kleros-v2#650]

**Comment by Arun9650** [comment]
BEFORE
![image](https://user-images.githubusercontent.com/76466509/230788318-2bdef66b-a00f-44c1-94fd-57d3dd2d4d83.png)

AFTER 
![image](https://user-images.githubusercontent.com/76466509/230788375-d3269f2d-0348-400a-9bb8-335b59298f1b.png)

is this what needed to be done ?
