### ISSUE TITLE
WalletConnect + Wagmi + Viem Migration

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#669]
**[WalletConnect](https://docs.walletconnect.com/2.0)**
**[Wagmi](https://wagmi.sh/)**
**[Viem](https://viem.sh/)**

- [x] #320 
- [x] #624 
- [x] #668

**Comment by Arun9650** [comment]
hi like to work on these issues

**Comment by Arun9650** [comment]
i have done the integration should i raise a pr?

**Comment by jaybuidl** [comment]
Hey @Arun9650 thanks for the contribution. Actually @alcercu has a PR in progress for this already #670. 
We'll see if we can cherry pick some useful changes from your PR 🙌.

**Comment by Arun9650** [comment]
Ohh that's great, I would like to contribute more in this project, it will be a pleasure to me if u redirect issues to me.

**Comment by jaybuidl** [comment]
UPDATE: this issue has been been expanded to include the migration to Viem.sh which was originally deemed unnecessary. But since then Wagmi has totally dropped ethers and adopted viem for its first stable release and future ones going forward.

https://viem.sh/docs/ethers-migration.html
