### ISSUE TITLE
Frontend Bugs : Community URLs missing, Cannot go back from Cases

### ISSUE THREAD

**Issue by abhiram11** [kleros/kleros-v2#671]
While inspecting the website to solve already raised issues, I stumbled upon a couple of minor issues that I thought could be brought to the notice of the dev team:

1. The links in the `Community` section of the landing page, such as `Kleros Forum`, `Snapshot`, `Talk with us`, etc., have been set to default at `google.com`. Quite a few of these links can be added from the contacts section at the bottom of the page.
2. In the `Latest Cases/ Cases` section, after clicking on any case and then clicking on `Back` button on the browser, the site does not direct anywhere. The back button works for routes WITHIN the cases though (Overview, Evidence, Voting, Appeal). The code for filters e.g., Appeal, Newest, etc. in the `Cases` page can also be added.
3. The Hamburger menu's `Notifications, Settings, and Help` sections have their `onClick` not defined yet.

### Note: I would like to contribute to the project and be a part of the dev team.
Let me know if you would like to assign me to these, or more issues related to YOUR priority. I would say my expertise order is Frontend > Backend > Solidity.
I lack the skillset of working with databases other than MongoDB or Firebase/store.

Edit: I saw that many of these are mentioned in #518 👍🏻 will add some code to fix it

**Comment by jaybuidl** [comment]
Hey Abhiram, thanks for your interest.

1. Another community member has just raised a PR already: #673

2. It might be an issue with the React Router, maybe @alcercu can advise.

3. Tracked as part of #272, the backend for this is being worked out.

**Comment by jaybuidl** [comment]
Issue 2. can be addressed in #691
