### ISSUE TITLE
Update the icons (Court page)

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#686]
Current
![image](https://user-images.githubusercontent.com/22213980/231133579-e098a3bf-ab3b-4edd-b2f8-20e1b9376015.png)

Figma
![image](https://user-images.githubusercontent.com/22213980/231133460-2537e326-3a74-42ce-b297-ecd103da7669.png)

**Comment by Arun9650** [comment]
is this good 
![image](https://user-images.githubusercontent.com/76466509/231946603-67f0edc9-59df-47ca-858c-5ef1e86ac7d4.png)

**Comment by jaybuidl** [comment]
[Before (left)](https://deploy-preview-510--kleros-v2.netlify.app/#/courts/1/purpose)  |  [After (right)](https://deploy-preview-734--kleros-v2.netlify.app/#/courts/1/purpose)
![image](https://github.com/kleros/kleros-v2/assets/22213980/945dc92e-92d9-4b9c-8b7b-c88a149e9cb4)
