### ISSUE TITLE
Latest Cases (Court page)

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#687]
Without the list view on mobile.

## Figma
⚠️  The label should be "Latest Cases" instead of Examples.
https://www.figma.com/file/b7DEUKDeHlOl4ocDTMv7UIhZ/Kleros?type=design&node-id=10896%3A572&mode=design&t=1UA6zf3TbA6yqIgf-1

## Preview
![image](https://github.com/kleros/kleros-v2/assets/22213980/a5b2fd87-eeeb-450f-8a92-56bbe5b55131)

**Comment by Zishan-7** [comment]
Hey @jaybuidl 👋🏻
I would like to work on the issue, can you assign it to me?

**Comment by jaybuidl** [comment]
Hey @Zishan-7, very cool, good luck! 

I've added the link to Figma in the description.

**Comment by Zishan-7** [comment]
Hey @jaybuidl 👋🏻
I am trying to set up the repo locally but I am getting some errors 

I followed the steps mentioned in the readme file.

**Step 1:**  `yarn workspace @kleros/kleros-v2-contracts start-local`
**Step 2:**  `yarn workspace @kleros/kleros-v2-subgraph start-local-indexerl`

But when I am running this command: `yarn workspace @kleros/kleros-v2-subgraph rebuild-deploy-local`
I am facing this issue

<img width="699" alt="Screenshot 2023-07-28 at 12 18 40 PM" src="https://github.com/kleros/kleros-v2/assets/72738005/52c496a9-72c5-49c3-aef1-7b9a1647cf1b">



Also in the `Klerosv2/web/sec/hooks/queries/getPNKBalance.ts` file, there is a missing module: 


<img width="987" alt="Screenshot 2023-07-28 at 12 24 51 PM" src="https://github.com/kleros/kleros-v2/assets/72738005/87eab551-e53f-4c4d-a138-b4361be0af44">


Can you please help me out with this?

Thanks  🙌🏼

**Comment by Zishan-7** [comment]
> Hey @jaybuidl 👋🏻 While trying to set up the repo locally I am getting some errors
> 
> I followed the steps mentioned in the readme file.
> 
> **Step 1:** `yarn workspace @kleros/kleros-v2-contracts start-local` **Step 2:** `yarn workspace @kleros/kleros-v2-subgraph start-local-indexerl`
> 
> But when running this command: `yarn workspace @kleros/kleros-v2-subgraph rebuild-deploy-local` I am facing this issue
> 
> <img alt="Screenshot 2023-07-28 at 12 18 40 PM" width="699" src="https://user-images.githubusercontent.com/72738005/256745414-52c496a9-72c5-49c3-aef1-7b9a1647cf1b.png">
> 
> Can you please help me out with this?
> 
> Thanks 🙌🏼

I have created an issue for this at #1066
