### ISSUE TITLE
Smart Contract Accounts support via ERC-1271

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#833]
Currently, smart contract accounts are able to stake in the court but 
- NOT able to authenticate via SIWE, so can't submit any evidence
- NOT able to commit/reveal in courts where hiddenVotes are enabled.

We are planning to enable hiddenVotes in the General Court in v2. 

Hidden votes are already enabled in the xDAI KlerosLiquid general court and both xDAI/Ethereum Spanish general court.

#### EIP1271
- [Why EIP1271?](https://ethereum.org/en/developers/tutorials/eip-1271-smart-contract-signatures/#why-does-eip-1271-exist)
- https://github.com/wevm/wagmi/discussions/90
- [Implementation by Gnosis Safe's Fallback handler](https://github.com/safe-global/safe-smart-account/blob/90d7caa8d3fc99941de9d0b7c463d460eb56351d/contracts/Safe.sol#L214-L343)
- [Example of EIP1271 signature verification](https://github.com/snapshot-labs/snapshot.js/blob/master/src/sign/eip1271.ts)
- https://github.com/Uniswap/web3-react/tree/main/packages/gnosis-safe

#### Commit/Reveal implementation in v1
  - [Web3Salt.js](https://github.com/kleros/court/blob/master/src/temp/web3-salt.js)
  - [Web3Salt usage during commit/reveal](https://github.com/kleros/court/blob/master/src/components/case-details-card.js#L214)

**Comment by fnanni-0** [comment]
Beware that some smart contract wallets like gnosis Safe don't support `send()` and `transfer()`. You can stake but won't get the arbitration fees.

**Comment by jaybuidl** [comment]
Thanks @fnanni-0 that's good to know

**Comment by Harman-singh-waraich** [comment]
As of this date:
- Siwe verification works with Smart contract wallets (Gnosis Safe).
- Committing works , Reveal has not been tested yet ( tested on localhost)
