### ISSUE TITLE
UX: policy disambiguation

### ISSUE THREAD

**Issue by jaybuidl** [kleros/kleros-v2#914]
![image](https://github.com/kleros/kleros-v2/assets/22213980/d8a3ef25-438c-4294-8df9-8806ecf25794)

- Court Policy
- Policy -> Dispute Policy

**Comment by brunovjk** [comment]
Hi everyone! I'm new to contributing to Kleros and I'm interested in working on this task. Has anyone already started working on it? If not, can I help with this issue?
